import { precacheAndRoute } from 'workbox-precaching'

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// Push Event: Listen for incoming alert notifications
self.addEventListener('push', (event) => {
  const data = event.data ? event.data.json() : { title: 'Alert', body: 'New notification from Iron Sight' };

  const options = {
    body: data.body,
    icon: '/icon-192.png',
    badge: '/icon-192.png',
    vibrate: [100, 50, 100]
  };

  event.waitUntil(
    self.registration.showNotification(data.title, options)
  );
});